### ISSUE TITLE
Yedek

### ISSUE THREAD

**Issue by Skips1** [molla202/CreditCoin-CTC#1]
Hocam neyi yedeklememiz gerekiyor?
<img src="https://media2.giphy.com/media/df2hrDO6GYorzi5AxQ/giphy.gif?cid=ecf05e47rarmz0j5rs76m64uhk16nq8s48lp99qq1azrgh29&rid=giphy.gif&ct=g" align="center" height="150" width="300" />

**Comment by molla202** [comment]
taşımak istiyorsan baska yere kur eşleşme bitince ilkini durdur 2cisini seedleri girerek stake işlemi kodunu yazarak yap .
bildiğim kadarı ile mnemonickler yeterli ama işi garantiye alalım.

**Comment by Skips1** [comment]
Yok yani Taşımayacağımda sunucuya bir şey olur falan dosya mosya yedeklenmesi gerekiyorsa yedekliyelim dedim de tamamdır kaptan problem yok
